import Link from "next/link";
import Button from "@/components/Button";
import { EyebrowBadge } from "@/components/Badge";
import StatGrid from "@/components/StatGrid";
import { BigTestimonial } from "@/components/TestimonialCard";
import FAQAccordion from "@/components/FAQAccordion";
import PricingCard from "@/components/PricingCard";
import CreatorMarketplaceMock from "@/components/CreatorMarketplaceMock";
import LinkedInPostCard from "@/components/LinkedInPostCard";
import StepSection from "@/components/StepSection";
import { PRICING_PLANS } from "@/lib/pricing";
import {
  FitListMock,
  BriefBuilderMock,
  CollaborationsMock,
  PipelineMock,
  PaymentMock,
} from "@/components/StepMocks";

const posts = [
  {
    name: "Thomas Higadère",
    role: "Creator · B2B & AI · 34K followers",
    hook: "How AI changed our prospecting workflow for wealth managers and private bankers.",
    impressions: "42.8K",
    clicks: "312",
    leads: "18",
    brand: "Naano",
  },
  {
    name: "Robin Tempe",
    role: "Creator · Sales & AI · 12K followers",
    hook: "I run my entire prospecting workflow through an AI. Here is how.",
    impressions: "9K",
    clicks: "100",
    leads: "50",
    brand: "Naano",
  },
  {
    name: "Eric Djavid",
    role: "Sales Leader · B2B · 40K followers",
    hook: "Most sales teams spend 80% of their time on the wrong leads. Here is how I changed that.",
    impressions: "20K",
    clicks: "350",
    leads: "80",
    brand: "Naano",
  },
  {
    name: "Marina Panova",
    role: "Content Creator · B2B · 34K followers",
    hook: "How I build my 30-day LinkedIn content system, the exact playbook.",
    impressions: "100K",
    clicks: "1,600",
    leads: "320",
    brand: "Naano",
  },
];

const faqs = [
  {
    question: "What is Naano?",
    answer:
      "Naano is a B2B LinkedIn creator marketplace: companies discover and book vetted creators for sponsored LinkedIn campaigns, each at a fixed price per post set by the creator. The marketplace spans creators from niche voices with around 1,000 followers to established B2B creators with audiences of several hundred thousand.",
  },
  {
    question: "How does Naano find the right creators?",
    answer:
      "Every creator is vetted and tagged by vertical (sales, RevOps, devtools, HR-tech, product, marketing). We match campaigns using audience fit, not just follower count, so a 3K-follower creator in your exact niche can outrank a 100K generalist.",
  },
  {
    question: "Which networks do you support?",
    answer: "LinkedIn is the primary network, with growing support for X and YouTube creators.",
  },
  {
    question: "How does per-post pricing work?",
    answer:
      "Each creator sets a flat price per published post, starting from €20. You see the exact price before you book, no cost per click, impression, or lead.",
  },
  {
    question: "How does attribution work?",
    answer:
      "Every post ships with a tracked CTA link, so you see clicks, leads and pipeline generated per post and per creator in one dashboard.",
  },
  {
    question: "Do you handle creator payouts?",
    answer:
      "Yes. Once you approve the published post, the creator is paid automatically via Stripe Connect. Naano handles invoices and approval records.",
  },
  {
    question: "What's the difference between Free and Done for you?",
    answer:
      "Self-Serve is €0/month and you run campaigns yourself. Managed Campaigns is €700/month and the Naano team handles creator sourcing, briefs, and reporting end to end.",
  },
  {
    question: "Can I upgrade or cancel anytime?",
    answer: "Both plans are month-to-month. Upgrade, downgrade, or cancel whenever you like.",
  },
];

export default function Home() {
  return (
    <>
      {/* Hero */}
      <section className="hero-gradient border-b border-border">
        <div className="mx-auto max-w-4xl px-6 pb-20 pt-20 text-center sm:pt-28">
          <div className="flex justify-center">
            <EyebrowBadge>Where B2B brands work with creators</EyebrowBadge>
          </div>
          <h1 className="mx-auto mt-8 max-w-3xl text-4xl font-semibold leading-[1.08] tracking-tight text-ink sm:text-6xl">
            The B2B LinkedIn Creator Marketplace.
          </h1>
          <p className="mx-auto mt-6 max-w-xl text-lg text-muted">
            Find the creators your buyers already trust, launch campaigns in days, and track the
            clicks, leads and pipeline generated by every post.
          </p>
          <div className="mt-9 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
            <Button href="/register" arrow>
              Launch a campaign
            </Button>
            <Button href="#how-it-works" variant="ghost">
              See how Naano works →
            </Button>
          </div>
        </div>
      </section>

      {/* Testimonial */}
      <section id="what-people-think" className="border-b border-border bg-surface-alt px-6 py-24">
        <BigTestimonial
          quote="We manage €10M+ of influence budget every year. For B2B, Naano simply makes our life easier"
          highlight="easier"
          name="David Zmirov"
          role="CEO, Zmirov Communication · Influence agency"
        />
      </section>

      {/* Marketplace showcase */}
      <section className="border-b border-border px-6 py-24">
        <div className="mx-auto max-w-5xl">
          <div className="text-center">
            <EyebrowBadge>The Naano creator marketplace</EyebrowBadge>
            <h2 className="mx-auto mt-6 max-w-2xl text-3xl font-semibold tracking-tight text-ink sm:text-4xl">
              Work with all the best creators.
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-muted">
              Find the right B2B voices, compare their audience fit, and book every collaboration
              from one place.
            </p>
          </div>
          <div className="mt-14">
            <CreatorMarketplaceMock />
          </div>
          <div className="mt-10 grid grid-cols-1 gap-8 text-center sm:grid-cols-3">
            <div>
              <p className="text-2xl font-semibold text-ink">3,000+</p>
              <p className="mt-1 text-sm text-muted">vetted creators, specialist B2B voices</p>
            </div>
            <div>
              <p className="text-2xl font-semibold text-ink">100 countries</p>
              <p className="mt-1 text-sm text-muted">local expertise, genuinely global reach</p>
            </div>
            <div>
              <p className="text-2xl font-semibold text-ink">96%</p>
              <p className="mt-1 text-sm text-muted">matched to your buyers, not just followers</p>
            </div>
          </div>
        </div>
      </section>

      {/* How it works — numbered steps */}
      <section id="how-it-works" className="border-b border-border px-6 py-24">
        <div className="mx-auto max-w-3xl text-center">
          <EyebrowBadge>One platform, from brief to results</EyebrowBadge>
          <h2 className="mx-auto mt-6 max-w-xl text-3xl font-semibold tracking-tight text-ink sm:text-4xl">
            Run creator campaigns from one place.
          </h2>
          <p className="mx-auto mt-4 max-w-xl text-muted">
            Find the right voices, launch faster, and connect every post to measurable business
            results.
          </p>
        </div>

        <div className="mx-auto mt-14 max-w-xl">
          <StepSection number="01" title="Find creators your buyers trust">
            <FitListMock />
          </StepSection>
          <StepSection number="02" title="Build a campaign brief in minutes">
            <BriefBuilderMock />
          </StepSection>
          <StepSection number="03" title="Manage every collaboration">
            <CollaborationsMock />
          </StepSection>
          <StepSection number="04" title="Track reach, clicks, and leads">
            <PipelineMock />
          </StepSection>
          <StepSection number="05" title="Pay creators without the admin">
            <PaymentMock />
          </StepSection>
        </div>
      </section>

      {/* Real posts */}
      <section className="border-b border-border bg-surface-alt px-6 py-24">
        <div className="mx-auto max-w-6xl">
          <div className="text-center">
            <h2 className="text-3xl font-semibold tracking-tight text-ink sm:text-4xl">
              Real teams. Measurable pipeline.
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-muted">
              See how B2B teams turn creator trust into attributable demand with Naano.
            </p>
          </div>
          <div className="mt-14 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {posts.map((post) => (
              <LinkedInPostCard key={post.name} post={post} />
            ))}
          </div>
        </div>
      </section>

      {/* Results stat strip */}
      <section className="border-b border-border px-6 py-24">
        <div className="mx-auto max-w-4xl text-center">
          <h2 className="text-3xl font-semibold tracking-tight text-ink sm:text-4xl">
            Proven across thousands of campaigns.
          </h2>
          <div className="mt-14">
            <StatGrid
              stats={[
                { value: "5M+", label: "Impressions generated" },
                { value: "30K+", label: "Leads generated" },
                { value: "2,000+", label: "Creators on Naano" },
                { value: "5K+", label: "Posts published" },
              ]}
            />
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing-preview" className="border-b border-border bg-surface-alt px-6 py-24">
        <div className="mx-auto max-w-4xl text-center">
          <EyebrowBadge>Start free. Pay per post when you&apos;re ready.</EyebrowBadge>
          <h2 className="mx-auto mt-6 max-w-lg text-3xl font-semibold tracking-tight text-ink sm:text-4xl">
            Pricing.
          </h2>
          <p className="mx-auto mt-4 max-w-lg text-muted">
            Start free. Upgrade when you want your time back. Choose whether you want to run
            creator campaigns in-house or have Naano operate them.
          </p>
        </div>

        <div className="mx-auto mt-14 grid max-w-4xl grid-cols-1 gap-6 sm:grid-cols-2">
          <PricingCard
            plan={{
              ...PRICING_PLANS["self-serve"],
              features: PRICING_PLANS["self-serve"].features.slice(0, 4),
            }}
          />
          <PricingCard
            plan={{ ...PRICING_PLANS.managed, features: PRICING_PLANS.managed.features.slice(0, 4) }}
          />
        </div>
        <p className="mt-8 text-center text-sm text-muted-soft">
          Campaign spend is separate. No lock-in. Cancel anytime.
        </p>
      </section>

      {/* FAQ */}
      <section id="faq" className="border-b border-border px-6 py-24">
        <div className="mx-auto max-w-2xl">
          <div className="text-center">
            <h2 className="text-3xl font-semibold tracking-tight text-ink sm:text-4xl">
              Frequently asked questions.
            </h2>
            <p className="mt-4 text-muted">Everything you need to know before getting started.</p>
          </div>
          <div className="mt-12">
            <FAQAccordion items={faqs} />
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="hero-gradient px-6 py-24">
        <div className="mx-auto max-w-2xl text-center">
          <EyebrowBadge>Ready to launch?</EyebrowBadge>
          <h2 className="mx-auto mt-6 text-3xl font-semibold tracking-tight text-ink sm:text-4xl">
            Your next creator campaign starts here.
          </h2>
          <p className="mx-auto mt-4 max-w-md text-muted">
            Get a clear creator strategy, campaign format and estimated budget for your next
            launch.
          </p>
          <div className="mt-9 flex justify-center">
            <Button href="/book" arrow>
              Book a campaign call
            </Button>
          </div>
          <p className="mt-4 text-sm text-muted-soft">
            Prefer to start yourself?{" "}
            <Link href="/register" className="font-medium text-accent">
              Start for free →
            </Link>
          </p>
        </div>
      </section>
    </>
  );
}
